getToolByName: accept tool from mock module.
This is needed for me locally when running:

  bin/test -s Products.Archetypes -m test_pawidgets

No idea why Jenkins is happy.  Locally I get errors:

  TypeError: Object found is not a portal tool (portal_properties)

This is because those tests are accessing
self.context.portal_properties where self.context is an instance of
mock.Mock, so the portal_properties are also mock.Mock.