Fixed error introduced by previous commit r52328: AttributeError: 'NoneType' object has no attribute 'getTypeInfo'. Refs #8198
svn path=/plone.app.layout/trunk/; revision=52342